'use client'
import { useState } from 'react'
import Link from 'next/link'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import { useIsMobile } from '@/hooks/useIsMobile'

const GREEN = '#2D4A3E'
const CORAL = '#E8836A'
const CREAM = '#FAFAF5'
const BEIGE = '#F5F0E8'
const BODY  = '#4A5568'

const FAQ_SECTIONS = [
  {
    category: 'Getting Started',
    icon: '📖',
    questions: [
      {
        q: 'How do I personalize my book?',
        a: "Choose your book, type their name, and upload one clear photo of their face. Add a dedication if you want the first page to come from you. Most people are done in under five minutes.",
      },
      {
        q: 'Can I preview my book before I buy it?',
        a: "Yes. You'll see their character and every page before you pay. If something looks off, tell us and we'll rework it. No charge.",
      },
      {
        q: 'What kind of photo works best?',
        a: "A clear, well-lit, front-facing photo. Avoid heavy filters, sunglasses, or hats. The better the photo, the closer the likeness. If you're unsure, upload it and see how the preview looks.",
      },
    ],
  },
  {
    category: 'About the Books',
    icon: '✨',
    questions: [
      {
        q: 'What makes a Miloria book different?',
        a: "Three things. The stories are written by people, properly, not generated by swapping a name into a template. Every illustration is reviewed by a human before it goes anywhere near a printer. And it's a real hardcover: sewn, sturdy, made to be read at bedtime for years, not admired once and shelved.",
      },
      {
        q: 'Do you use AI to make the illustrations?',
        a: "We use AI to bring your child's likeness into illustrations that we've art-directed ourselves, and then a person checks every single page before it prints. If it doesn't look like them, it doesn't ship. The stories themselves are written by humans, start to finish.",
      },
      {
        q: 'What age range are the books for?',
        a: "Our books are designed to be treasured from babyhood through childhood. The stories and illustrations are suitable from birth, and the keepsake quality means they're just as meaningful for a 10-year-old as for a newborn.",
      },
    ],
  },
  {
    category: 'Shipping & Delivery',
    icon: '📦',
    questions: [
      {
        q: 'How long will it take to receive my book?',
        a: "Every book is made after you order it. Printing takes 1–3 business days, then 5–7 days to anywhere in Canada and the US, 10–14 internationally. Ordering for a specific date? Tell us at checkout and we'll make sure it lands in time.",
      },
      {
        q: 'Do you ship internationally?',
        a: "We do, worldwide. International orders usually arrive within 10–14 days of printing. Duties, if any, are charged by your country and not by us.",
      },
      {
        q: 'How will I know when my book has shipped?',
        a: "You'll receive an email confirmation once your order is placed, and a shipping notification with tracking details once your book is on its way.",
      },
    ],
  },
  {
    category: 'Quality & Guarantee',
    icon: '💝',
    questions: [
      {
        q: "What if I'm not happy with how my child's character turned out?",
        a: "Then we redo it. Tell us what's not right and we'll rework the illustrations. If it still isn't them, we'll refund you in full. A book with your child's face in it either looks like them or it isn't worth having.",
      },
      {
        q: 'Is every book reviewed before shipping?',
        a: "Yes. A real person checks every illustration before it goes to print, reviewing likeness, quality, and accuracy. If something isn't right, we fix it before it ships.",
      },
      {
        q: 'How do I get in touch?',
        a: "Email miloria@partyandpresents.com and you'll hear back from a person, usually the same day.",
      },
    ],
  },
]

function AccordionItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div style={{ borderBottom: '1px solid #E2EBE7' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', textAlign: 'left', background: 'none', border: 'none',
          padding: '20px 0', cursor: 'pointer', display: 'flex',
          justifyContent: 'space-between', alignItems: 'center', gap: 16,
        }}
      >
        <span style={{ fontFamily: 'Nunito, sans-serif', fontWeight: 700, fontSize: 15, color: GREEN, lineHeight: 1.5 }}>{q}</span>
        <span style={{ color: CORAL, fontSize: 22, fontWeight: 300, flexShrink: 0, transform: open ? 'rotate(45deg)' : 'none', transition: 'transform 0.2s', lineHeight: 1 }}>+</span>
      </button>
      {open && (
        <p style={{ fontFamily: 'Nunito, sans-serif', fontSize: 15, color: BODY, lineHeight: 1.8, margin: '0 0 20px', paddingRight: 32 }}>{a}</p>
      )}
    </div>
  )
}

export default function FAQPage() {
  const isMobile = useIsMobile()

  return (
    <div style={{ minHeight: '100vh', background: CREAM, fontFamily: 'Nunito, sans-serif' }}>
      <Header />

      {/* Hero */}
      <section style={{ background: GREEN, paddingTop: 70 }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: isMobile ? '56px 20px 64px' : '80px 24px 88px', textAlign: 'center' }}>
          <p style={{ fontFamily: 'Nunito, sans-serif', fontWeight: 700, fontSize: 12, color: 'rgba(255,255,255,0.45)', letterSpacing: 3, textTransform: 'uppercase', margin: '0 0 16px' }}>Help Centre</p>
          <h1 style={{ fontFamily: 'Playfair Display, serif', fontWeight: 900, fontSize: isMobile ? 36 : 56, color: '#fff', margin: '0 0 20px', lineHeight: 1.1 }}>
            We thought you<br /><span style={{ color: CORAL }}>might ask ✦</span>
          </h1>
          <p style={{ fontSize: isMobile ? 15 : 18, color: 'rgba(255,255,255,0.7)', margin: '0 auto', lineHeight: 1.8, maxWidth: 480 }}>
            The questions we get most, answered properly.
          </p>
        </div>
      </section>

      {/* FAQ sections */}
      <section style={{ maxWidth: 800, margin: '0 auto', padding: isMobile ? '48px 20px 64px' : '72px 24px 80px' }}>
        {FAQ_SECTIONS.map((section, si) => (
          <div key={si} style={{ marginBottom: 56 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
              <span style={{ fontSize: 24 }}>{section.icon}</span>
              <h2 style={{ fontFamily: 'Playfair Display, serif', fontWeight: 700, fontSize: isMobile ? 20 : 24, color: GREEN, margin: 0 }}>
                {section.category}
              </h2>
            </div>
            <div style={{ height: 2, background: '#E2EBE7', marginBottom: 4 }} />
            {section.questions.map((item, qi) => (
              <AccordionItem key={qi} q={item.q} a={item.a} />
            ))}
          </div>
        ))}

        {/* Contact prompt */}
        <div style={{ background: BEIGE, borderRadius: 20, padding: isMobile ? '32px 24px' : '40px 48px', textAlign: 'center' }}>
          <div style={{ fontSize: 36, marginBottom: 16 }}>💬</div>
          <h3 style={{ fontFamily: 'Playfair Display, serif', fontWeight: 700, fontSize: isMobile ? 20 : 24, color: GREEN, margin: '0 0 12px' }}>
            Still have a question?
          </h3>
          <p style={{ fontSize: 15, color: BODY, margin: '0 0 24px', lineHeight: 1.7 }}>
            <a href="mailto:miloria@partyandpresents.com" style={{ color: CORAL, fontWeight: 700, textDecoration: 'none' }}>
              miloria@partyandpresents.com
            </a>
            {' '}— you'll hear back from a person, usually the same day.
          </p>
          <Link href="/books" style={{ color: GREEN, fontFamily: 'Nunito, sans-serif', fontWeight: 800, fontSize: 14, textDecoration: 'none', border: `2px solid ${GREEN}`, padding: '10px 24px', borderRadius: 50, display: 'inline-block' }}>
            Choose a Book →
          </Link>
        </div>
      </section>

      {/* CTA */}
      <section style={{ background: GREEN, padding: isMobile ? '56px 20px' : '80px 24px', textAlign: 'center' }}>
        <h2 style={{ fontFamily: 'Playfair Display, serif', fontWeight: 900, fontSize: isMobile ? 30 : 44, color: '#fff', margin: '0 0 16px', lineHeight: 1.15 }}>
          Ready to create<br /><span style={{ color: CORAL }}>their book?</span>
        </h2>
        <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.6)', margin: '0 auto 36px', maxWidth: 420, lineHeight: 1.7 }}>
          See their character and every page before you pay.
        </p>
        <Link href="/books" style={{ background: CORAL, color: '#fff', fontFamily: 'Nunito, sans-serif', fontWeight: 800, fontSize: 16, padding: '16px 40px', borderRadius: 50, textDecoration: 'none', display: 'inline-block', boxShadow: '0 6px 28px rgba(232,131,106,0.45)' }}>
          Choose a Book →
        </Link>
      </section>

      <Footer />
    </div>
  )
}