'use client'
import { useState } from 'react'
import Link from 'next/link'

const GREEN = '#2D4A3E'
const CORAL = '#E8836A'
const CREAM = '#FAFAF5'
const BODY  = '#4A5568'

const FAQ_ITEMS = [
  {
    icon: '📖',
    q: 'How do I personalize my book?',
    a: "Choose your book, type their name, and upload one clear photo of their face. Add a dedication if you want the first page to come from you. Most people are done in under five minutes.",
  },
  {
    icon: '👀',
    q: 'Can I preview my book before I buy it?',
    a: "Yes. You'll see their character and every page before you pay. If something looks off, tell us and we'll rework it. No charge.",
  },
  {
    icon: '✨',
    q: 'What makes a Miloria book different?',
    a: "Three things. The stories are written by people, properly, not generated by swapping a name into a template. Every illustration is reviewed by a human before it goes anywhere near a printer. And it's a real hardcover: sewn, sturdy, made to be read at bedtime for years, not admired once and shelved.",
  },
  {
    icon: '🤖',
    q: 'Do you use AI to make the illustrations?',
    a: "We use AI to bring your child's likeness into illustrations that we've art-directed ourselves, and then a person checks every single page before it prints. If it doesn't look like them, it doesn't ship. The stories themselves are written by humans, start to finish.",
  },
  {
    icon: '📦',
    q: 'How long will it take to receive my book?',
    a: "Every book is made after you order it. Printing takes 1–3 business days, then 5–7 days to anywhere in Canada and the US, 10–14 internationally. Ordering for a specific date? Tell us at checkout and we'll make sure it lands in time.",
  },
  {
    icon: '🌍',
    q: 'Do you ship internationally?',
    a: "We do, worldwide. International orders usually arrive within 10–14 days of printing. Duties, if any, are charged by your country and not by us.",
  },
  {
    icon: '💝',
    q: "What if I'm not happy with how my child's character turned out?",
    a: "Then we redo it. Tell us what's not right and we'll rework the illustrations. If it still isn't them, we'll refund you in full. A book with your child's face in it either looks like them or it isn't worth having.",
  },
  {
    icon: '💬',
    q: 'How do I get in touch?',
    a: "Email miloria@partyandpresents.com and you'll hear back from a person, usually the same day.",
  },
]

function AccordionItem({ icon, q, a }: { icon: string; q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div style={{ borderBottom: '1px solid #E2EBE7' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', textAlign: 'left', background: 'none', border: 'none',
          padding: '20px 0', cursor: 'pointer', display: 'flex',
          alignItems: 'center', gap: 14,
        }}
      >
        <span style={{ fontSize: 20, flexShrink: 0 }}>{icon}</span>
        <span style={{ fontFamily: 'Nunito, sans-serif', fontWeight: 700, fontSize: 15, color: GREEN, flex: 1, lineHeight: 1.5 }}>{q}</span>
        <span style={{
          color: CORAL, fontSize: 22, fontWeight: 300, flexShrink: 0, lineHeight: 1,
          transform: open ? 'rotate(45deg)' : 'none', transition: 'transform 0.2s',
        }}>+</span>
      </button>
      {open && (
        <p style={{ fontFamily: 'Nunito, sans-serif', fontSize: 15, color: BODY, lineHeight: 1.8, margin: '0 0 20px', paddingLeft: 34, paddingRight: 32 }}>{a}</p>
      )}
    </div>
  )
}

export function FAQAccordion({ isMobile }: { isMobile: boolean }) {
  return (
    <section style={{ background: CREAM, padding: isMobile ? '48px 20px' : '72px 24px' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>

        <div style={{ textAlign: 'center', marginBottom: 40 }}>
          <h2 style={{
            fontFamily: 'Playfair Display, serif', fontWeight: 900,
            fontSize: isMobile ? 26 : 34, color: GREEN,
            margin: '0 0 12px', lineHeight: 1.25,
          }}>
            We thought you might ask <span style={{ color: CORAL }}>✦</span>
          </h2>
          <p style={{ fontFamily: 'Nunito, sans-serif', fontSize: 15, color: BODY, margin: 0, lineHeight: 1.7 }}>
            The questions we get most, answered properly.
          </p>
        </div>

        <div>
          {FAQ_ITEMS.map((item, i) => (
            <AccordionItem key={i} icon={item.icon} q={item.q} a={item.a} />
          ))}
        </div>

        <div style={{ textAlign: 'center', marginTop: 36, paddingTop: 32, borderTop: '1px solid #E2EBE7' }}>
          <p style={{ fontFamily: 'Nunito, sans-serif', fontSize: 14, color: BODY, margin: '0 0 16px', lineHeight: 1.7 }}>
            Still have a question?{' '}
            <a href="mailto:miloria@partyandpresents.com" style={{ color: CORAL, fontWeight: 700, textDecoration: 'none' }}>
              miloria@partyandpresents.com
            </a>
          </p>
          <Link href="/faq" style={{
            color: GREEN, fontFamily: 'Nunito, sans-serif', fontWeight: 800, fontSize: 13,
            textDecoration: 'none', border: `1.5px solid ${GREEN}`, padding: '8px 22px',
            borderRadius: 50, display: 'inline-block',
          }}>
            See all FAQs →
          </Link>
        </div>

      </div>
    </section>
  )
}